apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "lambda-qual-gate"
spec:
  stages:
    - name: "qa"
      sequences:
      - name: "test"
        properties:
          teststrategy: "functional"
      - name: "evaluation"